-- ==============================================================================
-- Script: Link LINE User ID to Staff
-- Description: เชื่อมโยง LINE account กับข้อมูลพนักงานในฐานข้อมูล
-- Usage: แทนค่า @staff_code และ @line_user_id แล้ว run script
-- ==============================================================================

-- ============================================
-- 📝 INSTRUCTIONS
-- ============================================
-- 1. แทนค่าตัวแปรด้านล่างนี้:
SET @staff_code = 'STAFF001';                  -- ← รหัสพนักงาน
SET @line_user_id = 'U1234567890abcdef';       -- ← LINE User ID
SET @line_display_name = 'John Doe';           -- ← ชื่อที่แสดงใน LINE (optional)

-- 2. Run script ทั้งหมดใน MySQL client


-- ============================================
-- STEP 1: ตรวจสอบข้อมูล Staff
-- ============================================

SELECT '🔍 STEP 1: ตรวจสอบข้อมูล Staff' AS step;

SELECT
  id,
  staff_code,
  CONCAT(first_name, ' ', last_name) AS full_name,
  department,
  position,
  email,
  phone,
  status,
  line_user_id AS current_line_user_id,
  is_line_linked AS currently_linked
FROM staffs
WHERE staff_code = @staff_code;

-- ตรวจสอบผลลัพธ์:
-- ✅ ถ้าเจอ 1 แถว → Staff มีอยู่ในระบบ
-- ❌ ถ้าไม่เจอ → Staff ไม่มีในระบบ (ต้องสร้างก่อน)


-- ============================================
-- STEP 2: เช็คว่า LINE User ID นี้ถูกใช้แล้วหรือไม่
-- ============================================

SELECT '🔍 STEP 2: ตรวจสอบ LINE User ID ซ้ำหรือไม่' AS step;

SELECT
  staff_code,
  CONCAT(first_name, ' ', last_name) AS full_name,
  department,
  line_user_id,
  line_display_name,
  is_line_linked
FROM staffs
WHERE line_user_id = @line_user_id;

-- ตรวจสอบผลลัพธ์:
-- ✅ ถ้าไม่เจอแถวใดๆ → LINE User ID ว่าง พร้อมใช้งาน
-- ⚠️  ถ้าเจอแถว → LINE User ID นี้ถูกเชื่อมโยงกับ Staff อื่นแล้ว


-- ============================================
-- STEP 3: เชื่อมโยง LINE User ID กับ Staff
-- ============================================

SELECT '✅ STEP 3: เชื่อมโยง LINE User ID กับ Staff' AS step;

UPDATE staffs
SET
  line_user_id = @line_user_id,
  line_display_name = @line_display_name,
  line_last_login_at = NOW(),
  is_line_linked = 1
WHERE staff_code = @staff_code
  AND status = 'active';  -- เชื่อมโยงได้เฉพาะ staff ที่ active

-- ตรวจสอบผล:
SELECT ROW_COUNT() AS rows_updated;
-- ✅ ถ้า rows_updated = 1 → สำเร็จ
-- ❌ ถ้า rows_updated = 0 → ไม่สำเร็จ (staff ไม่ active หรือไม่มี staff_code นี้)


-- ============================================
-- STEP 4: ยืนยันผลลัพธ์
-- ============================================

SELECT '✅ STEP 4: ยืนยันผลลัพธ์' AS step;

SELECT
  staff_code,
  CONCAT(first_name, ' ', last_name) AS full_name,
  department,
  position,
  email,
  phone,
  status,
  line_user_id,
  line_display_name,
  is_line_linked,
  line_last_login_at,
  CASE
    WHEN line_user_id IS NOT NULL AND is_line_linked = 1
    THEN '✅ เชื่อมโยงสำเร็จ'
    ELSE '❌ ยังไม่เชื่อมโยง'
  END AS link_status
FROM staffs
WHERE staff_code = @staff_code;


-- ============================================
-- STEP 5: Test Login (ทดสอบว่า login ได้หรือไม่)
-- ============================================

SELECT '🧪 STEP 5: ทดสอบการ Login' AS step;

-- จำลองการเช็ค login
SELECT
  id,
  staff_code,
  CONCAT(first_name, ' ', last_name) AS full_name,
  role,
  department,
  position,
  line_user_id,
  line_display_name,
  'JWT token will be generated by backend' AS token_note
FROM staffs
WHERE line_user_id = @line_user_id
  AND status = 'active';

-- ✅ ถ้าเจอแถว → Staff สามารถ login ด้วย LINE ได้แล้ว!
-- ❌ ถ้าไม่เจอ → ตรวจสอบว่า line_user_id หรือ status ถูกต้องหรือไม่


-- ==============================================================================
-- 🔄 ROLLBACK: ยกเลิกการเชื่อมโยง (ถ้าต้องการ)
-- ==============================================================================

-- ถ้าต้องการยกเลิกการเชื่อมโยง:
/*
UPDATE staffs
SET
  line_user_id = NULL,
  line_display_name = NULL,
  is_line_linked = 0
WHERE staff_code = @staff_code;

SELECT '🔄 ยกเลิกการเชื่อมโยงแล้ว' AS status;
*/


-- ==============================================================================
-- 📊 สรุปผลลัพธ์
-- ==============================================================================

SELECT
  '=====================================' AS separator
UNION ALL
SELECT '✅ เชื่อมโยง LINE กับ Staff สำเร็จ!'
UNION ALL
SELECT '=====================================' AS separator
UNION ALL
SELECT CONCAT('Staff Code: ', @staff_code)
UNION ALL
SELECT CONCAT('LINE User ID: ', @line_user_id)
UNION ALL
SELECT CONCAT('Display Name: ', @line_display_name)
UNION ALL
SELECT '=====================================' AS separator
UNION ALL
SELECT '🎉 Staff สามารถ Login ด้วย LINE ได้แล้ว!'
UNION ALL
SELECT '=====================================' AS separator;
